name: Test en develop

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test unitarios
    if: ${{ contains(github.event.head_commit.message, 'Verde') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkoutrepositorio
        uses: actions/checkout@v2

      - name: Configuracion entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: instalacion de librerias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test unitarios
        id: correr-pruebas
        run: python -m unittest -v tests/test_persona.py

      - name: Calculo de cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m

  merge-with-develop:
    name: Mezcla feature -> develop
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: checkoutrepositorio
        uses: actions/checkout@v2

      - name: Mezcla feature -> develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.head_ref }}
          target-branch: develop

        


    

