name: Test en develop
on:
  push:
    branches: [ develop ]
jobs:
  test:
    name: Test unitarios 
    runs-on: ubuntu-latest
    steps:
    - name: checkoutrepositorio
      uses: actions/checkout@v2
    - name: Configuracion entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.10'
    - name: instalacion de librerias
      run: |
        python -m pip install --upgrade pip
        python install -r requirements.txt
    - name: Test unitarios
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py
    - name: Calculo de cubrimiento
      id: cubrimineto
      run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m
        


    

